main: 
name: CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build_and_release:
    runs_on: ubuntu-latest,ubuntu,centos
    steps:
    - uses: action/checkout@v3
    - name: Run a one-line script
      run: echo Hello,world !
    - name: Run a multi-line  script
      run: 
        echo Add other actions to build,
        echo test,and deploy your project
