---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build-and-release:
    runs_on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Run a one-line script
        run: echo Hello,world !
      - name: Run a multi-line  script
        run: echo Add other actions to build, echo test,and deploy your project
